name: practice-deploy
on: push
jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v6
        with:
                node-version: 25
      - name: install dependensies
        run: npm ci
  lint-test:
    needs: check-out
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v6
        with:
                node-version: 25
      - name: install dependensies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: run
        run: npm run test
  built-deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v6
        with:
                node-version: 25
      - name: install dependensies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: deploy
        run: echo "Deploy In Progress.."
